server:
  port: 9000

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false
  application:
    name: demo
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://pureumdb.cqtam8phe2t1.ap-northeast-2.rds.amazonaws.com/pureum
    username: Pureum
    password: e!+8DRAks#9E$G
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
cloud:
  aws:
    credentials:
      access-key: AKIAXF6NZWF4MZMTDFU2
      secret-key: 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
    s3: #버킷이름
      bucket: pureum
    region: #S3 지역
      static: ap-northeast-2
    stack:
      auto: false
