server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://pureumdb.cqtam8phe2t1.ap-northeast-2.rds.amazonaws.com/pureum?serverTimezone=UTC
    username: Pureum
    password: e!+8DRAks#9E$G
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql