name: Deploy with Docker

on:
  push:
    branches: [ develop ]

env:
  DOCKER_IMAGE: ghcr.io/pureum-umc-app/label-go
  VERSION: ${{ github.sha }}
  NAME: label-go

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

<<<<<<< HEAD
=======
      - run: mkdir ./src/main/resources/firebase
      - run: touch ./src/main/resources/firebase/firebase_service_key.json
      - run: echo "${{ secrets.firebase_service_key }}" > ./src/main/resources/firebase/firebase_service_key.json

>>>>>>> 0326704317696c3db270915d4544b2c7ebbdb6a2
      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      ## gradle build
      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: web docker build and push
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} .
          docker push ${{ env.DOCKER_IMAGE }}

  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-go ]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Docker run
        run: |
          docker stop ${{ env.NAME }} && docker rm ${{ env.NAME }} && docker rmi ${{ env.DOCKER_IMAGE }}
          docker run -d -p 9000:9000 -e JAVA_OPTS=-Djasypt.encryptor.password=${{ secrets.JASYPT_KEY }} --name label-go --restart always ${{ env.DOCKER_IMAGE }}:latest